#!/bin/sh
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"

#urxvtd -f -q &
xrdb /home/bernd/.Xresources &
nitrogen --restore &
xcompmgr &
unclutter &
#lxpolkit &
#nm-applet &
thunar --daemon &
(conky | while read LINE; do xsetroot -name "$LINE"; done) &
#gnome-keyring-daemon --start --components=pkcs11, secrets, gpg, ssh &
#volumeicon &
#wmname LG3D
lxsession &